name: git-validate

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node LTS
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Validate git
      run: |
        npm run lint:commits
      env:
        CI: true
