name: test-lib

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node LTS
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
